---
- name: Trabajar con modulo parted
  hosts: ubuntu_server

  tasks:
    - name: Crear particion
      community.general.parted:
        device: /dev/sdb
        number: 1
        part_end: 5GiB
        state: present

    - name: Ver datos del sdb
      community.general.parted:
        device: /dev/sdb
        state: info
      register: datos
       

    - name: Ver informacion de sdb
      community.general.parted:
        device: /dev/sdb
        state: info
      register: datos

    - name: ver los datos
      ansible.builtin.debug:
      var: datos 
